/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_u4;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Secundaria extends javax.swing.JFrame {

    /**
     * Creates new form Secundaria
     */
    
       ConectarT con=new ConectarT();
          Connection reg=con.conexion();
          
    public Secundaria() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);
        setResizable(false);
        setVisible(true);
        getContentPane().setBackground(Color.WHITE);
        verTabla();
    }
    
    
     public void verTabla(){
           
              DefaultTableModel miModelo=new DefaultTableModel();
              miModelo.addColumn("Matricula");
              miModelo.addColumn("Nombre");
              miModelo.addColumn("Edad");
              miModelo.addColumn("Tutor");
              miModelo.addColumn("Grado");
              miModelo.addColumn("Actividad");
              
              String matri="",matri2="";
              String bin="";
              String []datos=new String[7];
        

              String  sql="SELECT * FROM alumno";
              
                 try {
                 Statement sentencia= reg.createStatement();
                 ResultSet rsa= sentencia.executeQuery(sql);
        
                 while (rsa.next()) {

               datos[0]=rsa.getString(1);//campos de la tabla de la base de datos
               datos[1]=rsa.getString(2);
               datos[2]=rsa.getString(3);
               datos[3]=rsa.getString(4);
               datos[4]=rsa.getString(5);
               datos[5]=rsa.getString(6);
               datos[6]=rsa.getString(7);


               bin=datos[6];
               if(bin.equals("1")){
                matri=datos[0];
               matri2=matri.substring(0,4);
                     System.out.println("matri"+matri2);
               if(matri2.equals("0704") || matri2.equals("0804") || matri2.equals("0904") ){
               miModelo.addRow(datos);
               }
               }
                } 
                }catch (SQLException ex) {
                Logger.getLogger(Primaria.class.getName()).log(Level.SEVERE, null, ex);
                }
                 tabla.setModel(miModelo);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setText("Secundaria");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Title 2", "Title 3", "Title 4", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
                int seleccion=tabla.getSelectedRow();
        String mod=tabla.getValueAt(seleccion,0).toString();
        String grado="";
        String monto="";
        String nomtu="";
        String num="";
        String dire="";
        String rfc="";
        String sql="";
        String []datos=new String[6]; 
        sql="SELECT * FROM alumno WHERE matricula='"+mod+"'";
            try{
                Statement sentencia=reg.createStatement();
                ResultSet rs= sentencia.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                }

                }catch(SQLException ex){
                Logger.getLogger(Primaria.class.getName()).log(Level.SEVERE,null,ex);
            }
             String matri=datos[0];
             String nom=datos[1];
             String edad=datos[2];
             String idt=datos[3];
             String idgrado=datos[4];
             String idact=datos[5];
           sql="SELECT * FROM tutor WHERE idtutor='"+idt+"'";      
           
           try{
                Statement sentencia=reg.createStatement();
                ResultSet rs= sentencia.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    
                }
                
                nomtu=datos[1];
                num=datos[2];
                dire=datos[3];
                rfc=datos[4];
                }catch(SQLException ex){
                Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE,null,ex);
            }
                
           sql="SELECT * FROM grado WHERE idgrado='"+idgrado+"'";      
           
           try{
                Statement sentencia=reg.createStatement();
                ResultSet rs= sentencia.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    
                }
                
                grado=datos[0];
                monto=datos[4];

                }catch(SQLException ex){
                Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE,null,ex);
            }
           
           sql="SELECT * FROM actividad WHERE idactividad='"+idact+"'";      
           
           try{
                Statement sentencia=reg.createStatement();
                ResultSet rs= sentencia.executeQuery(sql);
                while(rs.next()){
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
  
                }
                

                }catch(SQLException ex){
                Logger.getLogger(Secundaria.class.getName()).log(Level.SEVERE,null,ex);
            }
           
           Info obj1= new Info(matri,nom,edad,grado,monto,nomtu,num,dire,rfc,idact,idt);
           setVisible(false);
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secundaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secundaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
